---
title: "exp19_24_first_qpcr"
author: "YJ"
date: "July 15, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
read shit
```{r}
library(tidyverse)
dir=getwd()
qpcr<-data.frame(read.csv(file.path(dir, "exp19_24_first_CT.csv"), stringsAsFactors = FALSE))
qpcrMeta<-data.frame(read.csv(file.path(dir, "exp19_24_redo_metaData.csv"),stringsAsFactors = FALSE))

CT<-data.frame(matrix(qpcr$CT, ncol=2, byrow= TRUE))
colnames(CT)= c("CT1","CT2")
CT<- data.frame(CT,Gene = rep(c("CFTR","RPL32"), each = 72), qpcrMeta)
cf = which(CT$Gene == "CFTR")
rpl = which(CT$Gene == "RPL32")
```
set treatments as factors
```{r}
ASOtx<-unique(qpcrMeta$ASO)
ASOtx<-factor(ASOtx, levels = ASOtx)
CT$ASO<-factor(CT$ASO, levels =ASOtx) ## this was important for setting the order of lm x

```

Find 'NA' and record them 
```{r}
na<-  CT[is.na(CT[,"CT1"] | CT[,"CT2"]),]
CT[na$index,c("CT1","CT2")]<- apply(na[,c("CT1","CT2")],1,min)
```
calculate mean CT, dCT (CFTR - RPL32), and ddCT (normalize all dCT to dCT of NT)
```{r}
CT = data.frame(CT, mean_CT=apply(CT[,c("CT1","CT2")],1,mean, na.rm= TRUE))
CT$dCT = CT$mean_CT[cf]-CT$mean_CT[rpl]
NTdCT <- mean(CT$dCT[1:3])
CT$ddCT = CT$dCT-NTdCT
```
gene fold change
```{r}
CT$fc<-2^(-1*CT$ddCT)
```

Analyze by one-way ANOVA with Tukey's test
```{r}
plotarea<-CT[CT$Gene=="CFTR",]
plotarea<-plotarea[-c(7:9), ]
plotarea[plotarea$fc>50,"fc"]<-NA
a1<-aov(log2(fc) ~ ASO, data = plotarea)
a1Tukey<-TukeyHSD(a1)
a1pval<-a1Tukey$ASO[,"p adj"]

a1vsNT=data.frame(ASO = ASOtx[-3], pvals = c(0,a1pval[grep("-NT",names(a1pval))]))
a1vsNT$mean_fc = c(1,2^a1Tukey$ASO[grep("-NT",names(a1pval)),"diff"])

a1vsNT$significance = ifelse(a1vsNT$ASO == "NT", '',
  ifelse(a1vsNT$pvals<0.001,"***",
                         ifelse(a1vsNT$pvals<0.01,"**",
                                ifelse(a1vsNT$pvals<0.05,"*",'ns')
       )
)
)
```
linear regression
```{r}
lm1<-lm(log2(fc) ~ ASO, data = plotarea)
pvals1<-unlist(coef(summary(lm1))[,4])
pvals1<-data.frame(raw_pval= pvals1, p.adjust = p.adjust(pvals1, method = "BH"))
pvals1$significance = ifelse(pvals1$raw_pval >=0.9, '',
  ifelse(pvals1$p.adjust<0.001,"***",
                         ifelse(pvals1$p.adjust<0.01,"**",
                                ifelse(pvals1$p.adjust<0.05,"*",'ns')
       )
)
)
```

plot fc based on anova
```{r}
ggplot()+ 
  geom_boxplot(aes(x = plotarea$ASO,y=plotarea$fc,col=plotarea$ASO))+
  geom_jitter(aes(x = plotarea$ASO,y=plotarea$fc), size = 1) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none") +
  geom_text(aes(x =a1vsNT$ASO,y=a1vsNT$mean_fc+1.5,label=a1vsNT$significance ))
```
plot fc based on linear regression
```{r}
ggplot()+ 
  geom_boxplot(aes(x = plotarea$ASO,y=plotarea$fc,col=plotarea$ASO))+
  geom_jitter(aes(x = plotarea$ASO,y=plotarea$fc), size = 1) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none") +
  geom_text(aes(x =a1vsNT$ASO,y=a1vsNT$mean_fc+1.5,label=pvals1$significance ))
```